PUT http://localhost:8080/api/endereco
Content-Type: application/json

{
  "id": 1,
  "cep": "01001-000",
  "logradouro": "Praça da Sé",
  "complemento": "lado ímpar",
  "bairro": "Sé",
  "cidade": "Dos sonhos",
  "uf": "SP",
  "localizacao": null
}
