###
POST http://localhost:8080/api/endereco
Content-Type: application/json

{
  "cep": "25550-644",
  "logradouro": "Rua Quati",
  "complemento": "lado ímpar",
  "bairro": "Sé",
  "localidade": "São Paulo",
  "uf": "SP"
}
