###
PUT http://localhost:8080/api/produto
Content-Type: application/json

{
  "codigo": 1,
  "nome": "Produto teste",
  "descricaoProduto": "teste",
  "valor": 15000,
  "marcaModeloList": [
    {
      "codigo": 1,
      "descricao": "teste de cadastra marca",
      "status": "ATIVO"
    }
  ],
  "categoriaModelo": {
    "codigo": 1,
    "descricao": "cadastro categoria",
    "status": "ATIVO"
  },
  "quantidade": 10,
  "status": "ATIVO"
}