###
POST http://localhost:8080/api/pessoa
Content-Type: application/json

{
  "nome": "Teste",
  "cpf": "00000",
  "sexo": "",
  "dataNascimento": "",
  "telefone": "",
  "celular": "",
  "enderecoModeloList": [
    {
      "codigo": 1,
      "cep": "01001-000",
      "logradouro": "Praça da Sé",
      "bairro": "Sé",
      "localidade": "São Paulo",
      "uf": "SP"
    }
  ]
}