###
PUT http://localhost:8080/api/pessoa
Content-Type: application/json

{
  "codigo": 1,
  "nome": "Teste de autlização",
  "cpf": "13521089096",
  "celular": "(68) 3558-2323",
  "telefone": "(68) 3558-2323",
  "sexo": "feminino",
  "dataNascimento": "1983-18-03"
}